### ISSUE TITLE
Opened tabs immediately closed on Firefox 74

### ISSUE THREAD

**Issue by jrogov** [chronakis/firefox-sticky-window-containers#5] opened 2020-03-13 12:47 UTC
In the new version 74 of Firefox I can't open a new tab within container. It is as if it is opened and immediately closed. 

I assume that it was because of Tree Style Tabs, but it was confirmed on the different setup.

It appears to be an issue with the new version of Firefox, given that another extension called "Sticky Containers" behave the same way. 
  

**To Reproduce**
1. Open new window
2. Set any non-default container for the first tab
3. Try to open new tab with Ctrl-T (Cmd-T)

**Expected behavior**
Tab must be opened.

**Desktop (please complete the following information):**
- OS: MacOS/Linux
- Browser: Firefox 
- Version: 74

**Comment by xrad** [comment] 2020-03-14 08:19
I can confirm this issue.

**Comment by Grenaid** [comment] 2020-03-16 14:35
I also had this issue, and narrowed it down (for me at least) to one tab in the window being a local file.  Once I closed the local html file, everything worked as normal.

edit: slightly more complicated.  The addons window also causes problems, and once a window is "poisoned" you need to drag tabs to a new window to start over.  Annoying.

**Comment by chronakis** [comment] 2020-03-16 17:15
Thank you @arikai for the detailed description. Although I can't reproduce it myself, I have a suspicion and I will make a new version that reports some information in the console to help identify it.

The add-on needs an exclusion list of URLs that do not have the standard things (history, cookies etc), such as the preferences page or the new tab to avoid trying to take them over. I suspect that this black list is not complete and needs to be kept up to date.

I am working on a new version with improved logging on the Browser Console. Once I will publish it, I will reply here and then we can find what causes.

Many thanks.

Yiannis

**Comment by xrad** [comment] 2020-03-16 18:23
FWIW another datapoint WRT reproducing this: with any non-default custom container being the first tab, Cmd-T does not work as @arikai described. A new tab briefly pops up and is destroyed immediately. Same happens when you press the + button for a new tab. However, right clicking the + and manually selecting the container in question does work as expected (for me.) Codewise there should be no difference for the operations excect the container selection, so perhaps this may give you some more hints.

**Comment by chronakis** [comment] 2020-03-19 01:59
Thank you all for your feedback. Turns out that the trick to reproduce the issue was to configure firefox to use a blank page (about:newtab) as the new tab instead of the default "Firefox home". This is now fixed with [Douwe Maan's](https://github.com/DouweM) patch and released already. I hope this fixes the problem for you.

**Comment by xrad** [comment] 2020-03-19 06:15
Thanks a lot @chronakis and @DouweM for the swift respsone, it appears to work fine now on my work machine. Will check again later on my other box.

Edit: worked well everywhere!

**Comment by TaiSHiNet** [comment] 2020-03-19 14:35
Can confirm the update fixes it.

**Comment by chronakis** [comment] 2020-03-22 22:14
Thank you very much @xrad and @TaiSHiNet  for your feedback.

I will close this issue now and we will reopen it, if it is not fixed 100%

**Closed as completed by chronakis** 2020-03-22 22:14 UTC
