### ISSUE TITLE
When opening a new tab, cursor should be placed in the address bar

### ISSUE THREAD

**Issue by alexcetto** [chronakis/firefox-sticky-window-containers#2] opened 2019-08-19 11:49 UTC
**Is your feature request related to a problem? Please describe.**
When opening a new blank tab, the focus should be in the address bar. Right now, we lose focus when the tab is reopening as the good container category.
This is the default behaviour in Firefox.

**Describe the solution you'd like**
I would like the extension to be able to detect if it is a blank tab and refocus in the address bar.

**Describe alternatives you've considered**
I don't think of any suitable alternatives.

**Additional context**
What is happening at the moment:
<img width="583" alt="Screenshot 2019-08-19 at 13 47 29" src="https://user-images.githubusercontent.com/2983133/63263104-fa773280-c287-11e9-8c37-47c6c649f17b.png">
What I would want to see:
<img width="468" alt="Screenshot 2019-08-19 at 13 47 45" src="https://user-images.githubusercontent.com/2983133/63263145-0d8a0280-c288-11e9-9892-320523f531e8.png">

Thank you for your extension. This is exactly the sort of behaviour I want when using container tabs!

edit: The description text was removed.

**Comment by chronakis** [comment] 2019-11-20 14:51
Hello,

Thank you for reporting this and apologies for missing it completely until I received another notification today.

I haven't managed to reproduce this. I am using windows and mac, both stable and nightly Firefox. If you still have the issue, can you please let me know what OS you are using? I still need to set a VM with Linux to test this there.

**Comment by the21st** [comment] 2020-02-25 11:53
Happens to me on MacOS 10.14.6, Firefox 73.0.1

**Comment by nimbling** [comment] 2020-03-10 10:47
Happens to me on MacOS 10.15.2, Firefox 73.0.1
Is "containers theme" maybe interfering?

**Comment by chronakis** [comment] 2020-03-10 23:47
I just tried it in MacOS 10.15.3 with Firefox 73 and then 74 and the nightly build. I get the cursor properly focused on the address bar.

@nimbling , I also tried it with the containers theme (https://addons.mozilla.org/en-GB/firefox/addon/containers-theme/?src=search) and still works as expected.

I am not sure what to add in the logging to debug this. Could it be some other extension that causes it?

If anyone of you wants to disable all other extensions and give it a go, it could be useful.

Thanks

**Comment by nimbling** [comment] 2020-03-12 12:19
I disabled all other extensions, except sticky and the container one. Still happened, so strange.
Could you perhaps force the focus action, rather than rely on what's there?

**Comment by TaiSHiNet** [comment] 2020-03-23 14:33
I had this issue and it has been fixed as of last update (Firefox 74 and Sticky Containers 1.0.2)

**Comment by chronakis** [comment] 2020-03-24 15:00
Thank you @TaiSHiNet, very much appreciated! I suspect I could not reproduce this for the same reason I mentioned in the other issue. I had the default new tab setting.

I will close this and will reopen, if it happens to someone else.

**Closed as completed by chronakis** 2020-03-24 15:00 UTC
